//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeRepair.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public Appointments()
        {
            this.ServicesAppointment = new HashSet<ServicesAppointment>();
        }
    
        public int Id { get; set; }
        public int Id_Client { get; set; }
        public int Id_Master { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public int Id_Status { get; set; }
        public Nullable<int> Id_Feedback { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Feedback Feedback { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ServicesAppointment> ServicesAppointment { get; set; }
    }
}
