//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeRepair.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public Feedback()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int Id { get; set; }
        public string Comments { get; set; }
        public System.DateTime date { get; set; }
        public int Mark { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}
