//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeRepair.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLeaves
    {
        public int Id { get; set; }
        public int Id_Master { get; set; }
        public Nullable<int> Id_Vacation { get; set; }
        public Nullable<int> Id_SickLeave { get; set; }
    
        public virtual SickLeaves SickLeaves { get; set; }
        public virtual User User { get; set; }
        public virtual Vacations Vacations { get; set; }
    }
}
