//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeRepair.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public int Id_Chat { get; set; }
        public int Id_Sender { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SendDate { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual User User { get; set; }
    }
}
