//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeRepair.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoeRepairEntities : DbContext
    {
        public ShoeRepairEntities()
            : base("name=ShoeRepairEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appointments> Appointments { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Chats> Chats { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<MasterLeaves> MasterLeaves { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<Profile> Profile { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<ServicesAppointment> ServicesAppointment { get; set; }
        public DbSet<SickLeaves> SickLeaves { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Vacations> Vacations { get; set; }
    }
}
