//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeRepair.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesAppointment
    {
        public int Id { get; set; }
        public int Id_Services { get; set; }
        public int Id_Appointment { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Appointments Appointments { get; set; }
        public virtual Services Services { get; set; }
    }
}
